import type { Metric } from '@/lib/types';

export type GlossaryCategory =
  | 'physique'
  | 'acidite'
  | 'azote'
  | 'mineraux'
  | 'gaz'
  | 'lumiere'
  | 'biologie';

export interface GlossarySource {
  label: string;
  url: string;
}

export interface GlossaryEquation {
  label: string;
  formula: string;
  applicability: string;
}

export interface GlossaryEntry {
  id: string;
  term: string;
  symbol: string;
  unit: string;
  category: GlossaryCategory;
  metric?: Metric;
  definition: string;
  utility: string;
  chemistry: string;
  influencedBy: string[];
  related: string[];
  equations: GlossaryEquation[];
  cautions: string[];
  sources: GlossarySource[];
}

export const GLOSSARY_CATEGORY_LABELS: Record<GlossaryCategory, string> = {
  physique: 'Physique de l’eau',
  acidite: 'Acidité, alcalinité et dureté',
  azote: 'Cycle de l’azote',
  mineraux: 'Ions et minéraux',
  gaz: 'Gaz dissous et carbone',
  lumiere: 'Lumière et production primaire',
  biologie: 'Biologie et filtration',
};

const SOURCES = {
  iupacPh: {
    label: 'IUPAC Gold Book — pH',
    url: 'https://goldbook.iupac.org/terms/view/P04524',
  },
  sandreO2: {
    label: 'Sandre — calcul du taux de saturation en oxygène',
    url: 'https://mdm.sandre.eaufrance.fr/node/414781',
  },
  usgsDo: {
    label: 'USGS DOTABLES — solubilité de l’oxygène',
    url: 'https://www.usgs.gov/tools/dotables',
  },
  bensonKrause: {
    label: 'Benson & Krause (1984) — solubilité de O₂',
    url: 'https://doi.org/10.4319/lo.1984.29.3.0620',
  },
  truesdale: {
    label: 'Truesdale, Downing & Lowden (1955)',
    url: 'https://doi.org/10.1002/jctb.5010050201',
  },
  emerson: {
    label: 'Emerson et al. (1975) — équilibre NH₃/NH₄⁺',
    url: 'https://doi.org/10.1139/f75-274',
  },
  epaAmmonia: {
    label: 'US EPA — critères ammoniaque pour la vie aquatique',
    url: 'https://www.epa.gov/wqc/aquatic-life-criteria-ammonia',
  },
  usgsAlkalinity: {
    label: 'USGS — Alkalinity and Water',
    url: 'https://www.usgs.gov/water-science-school/science/alkalinity-and-water',
  },
  usgsHardness: {
    label: 'USGS — Hardness of Water',
    url: 'https://www.usgs.gov/water-science-school/science/hardness-water',
  },
  usgsConductivity: {
    label: 'USGS — Specific electrical conductance',
    url: 'https://pubs.usgs.gov/publication/twri09A6.3',
  },
  usgsWater: {
    label: 'USGS — Water properties',
    url: 'https://www.usgs.gov/water-science-school/properties-water',
  },
  par: {
    label: 'Mõttus et al. — Photosynthetically Active Radiation',
    url: 'https://doi.org/10.1007/978-1-4419-0851-3_451',
  },
  parRadiometry: {
    label: 'Paradiso et al. (2023) — radiométrie et PPFD',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10310645/',
  },
  faoFeedAnalysis: {
    label: 'FAO — principes d’analyse des aliments aquacoles',
    url: 'https://www.fao.org/4/ab468e/AB468E01.htm',
  },
  rasFeeding: {
    label: 'Aquaculture International (2022) — alimentation, O₂ et excrétion de TAN en RAS',
    url: 'https://doi.org/10.1007/s10499-021-00821-3',
  },
  epaNitrification: {
    label: 'US EPA — stœchiométrie de la nitrification',
    url: 'https://nepis.epa.gov/Exe/ZyPURL.cgi?Dockey=P100GE8B.TXT',
  },
};

export const SCIENTIFIC_GLOSSARY: GlossaryEntry[] = [
  {
    id: 'temperature',
    term: 'Température',
    symbol: 'T',
    unit: '°C',
    category: 'physique',
    metric: 'temperature',
    definition: 'Mesure de l’état thermique de l’eau. EcoBiome l’affiche en degrés Celsius (°C).',
    utility: 'Elle agit sur le métabolisme des organismes, la vitesse des réactions, la solubilité des gaz et plusieurs équilibres chimiques.',
    chemistry: 'Grandeur physique ; pas de formule chimique propre.',
    influencedBy: ['chauffage', 'température de l’air', 'rayonnement', 'évaporation', 'volume et inertie thermique'],
    related: ['oxygen', 'oxygen_saturation', 'tan', 'ammonia', 'ph'],
    equations: [],
    cautions: ['Une température “idéale” dépend des espèces et du stade de vie.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'ph',
    term: 'pH — potentiel hydrogène',
    symbol: 'pH / H⁺',
    unit: 'sans unité',
    category: 'acidite',
    metric: 'ph',
    definition: 'Le pH décrit l’acidité/basicité via l’activité des ions hydrogène H⁺ en solution.',
    utility: 'Il conditionne la physiologie des organismes, la stabilité chimique et la fraction toxique d’ammoniac NH₃.',
    chemistry: 'Ion concerné : H⁺. Le nom usuel « potentiel hydrogène » est pédagogique ; la définition rigoureuse porte sur l’activité de H⁺.',
    influencedBy: ['KH / alcalinité', 'CO₂', 'photosynthèse', 'respiration', 'nitrification', 'eau de remplacement'],
    related: ['kh', 'co2', 'tan', 'ammonia'],
    equations: [
      {
        label: 'Définition IUPAC',
        formula: 'pH = −log₁₀(aH⁺)',
        applicability: 'Définition thermodynamique fondée sur l’activité de l’ion hydrogène.',
      },
    ],
    cautions: ['Le pH n’est pas une concentration directe de H⁺ mesurée isolément.', 'La plage souhaitable dépend des espèces.'],
    sources: [SOURCES.iupacPh],
  },
  {
    id: 'oxygen',
    term: 'Oxygène dissous',
    symbol: 'O₂',
    unit: 'mg/L',
    category: 'gaz',
    metric: 'oxygen',
    definition: 'Concentration de dioxygène moléculaire O₂ dissous dans l’eau.',
    utility: 'Indispensable à la respiration des animaux et à de nombreux microorganismes aérobies, dont les nitrifiants.',
    chemistry: 'Formule moléculaire : O₂.',
    influencedBy: ['température', 'pression atmosphérique', 'salinité', 'aération', 'photosynthèse', 'respiration', 'décomposition organique'],
    related: ['oxygen_saturation', 'temperature', 'salinity', 'tss', 'biofilter'],
    equations: [
      {
        label: 'Solubilité simplifiée en eau douce',
        formula: 'Cs(T) = 14,64 − 0,4227T + 0,009937T² − 0,0001575T³ + 0,000001125T⁴',
        applicability: 'Approximation Sandre à 1013 mbar et salinité nulle ; Cs en mg/L et T en °C.',
      },
    ],
    cautions: ['Pour un calcul précis hors pression standard ou en eau saline, pression et salinité doivent être intégrées.'],
    sources: [SOURCES.sandreO2, SOURCES.usgsDo, SOURCES.bensonKrause, SOURCES.truesdale],
  },
  {
    id: 'oxygen_saturation',
    term: 'Taux de saturation en oxygène',
    symbol: 'Sat O₂',
    unit: '%',
    category: 'gaz',
    metric: 'oxygen_saturation',
    definition: 'Rapport entre l’oxygène dissous mesuré et la concentration d’équilibre attendue dans les conditions considérées.',
    utility: 'Permet de distinguer une concentration brute en mg/L de la proximité réelle avec la saturation.',
    chemistry: 'Concerne le dioxygène O₂ dissous.',
    influencedBy: ['O₂ mesuré', 'température', 'pression atmosphérique', 'salinité'],
    related: ['oxygen', 'temperature', 'salinity'],
    equations: [
      {
        label: 'Saturation simplifiée Sandre',
        formula: 'Sat O₂ (%) = O₂mesuré × 100 / Cs(T)',
        applicability: 'Avec Cs(T) calculé pour 1013 mbar et salinité nulle dans la méthode simplifiée.',
      },
    ],
    cautions: ['Une supersaturation >100 % est possible, notamment lors d’une photosynthèse intense ou de variations rapides de pression/température.'],
    sources: [SOURCES.sandreO2, SOURCES.usgsDo],
  },
  {
    id: 'tan',
    term: 'Azote ammoniacal total',
    symbol: 'TAN = NH₃-N + NH₄⁺-N',
    unit: 'mg N/L',
    category: 'azote',
    metric: 'tan',
    definition: 'Somme de l’azote présent sous les formes ammoniac non ionisé NH₃ et ammonium NH₄⁺, exprimée en masse d’azote.',
    utility: 'C’est la grandeur de base pour évaluer la charge ammoniacale avant de calculer la fraction NH₃.',
    chemistry: 'Équilibre : NH₄⁺ ⇌ NH₃ + H⁺.',
    influencedBy: ['excrétion animale', 'nourrissage', 'décomposition', 'biofiltration', 'pH', 'température'],
    related: ['ammonia', 'ph', 'temperature', 'nitrite', 'biofilter'],
    equations: [
      {
        label: 'Relation conceptuelle',
        formula: 'TAN = NH₃-N + NH₄⁺-N',
        applicability: 'Les deux termes doivent être exprimés sur la même base azote (N).',
      },
    ],
    cautions: ['Ne pas confondre mg N/L avec mg/L de NH₃ ou NH₄⁺.'],
    sources: [SOURCES.emerson, SOURCES.epaAmmonia],
  },
  {
    id: 'ammonia',
    term: 'Ammoniac non ionisé',
    symbol: 'NH₃',
    unit: 'mg/L ou mg N/L',
    category: 'azote',
    metric: 'ammonia',
    definition: 'Forme moléculaire non ionisée de l’ammoniac dissous. Sa fraction dans le TAN augmente fortement avec le pH et varie avec la température.',
    utility: 'La forme NH₃ est particulièrement importante pour l’évaluation du risque toxique chez les organismes aquatiques.',
    chemistry: 'Équilibre : NH₄⁺ ⇌ NH₃ + H⁺.',
    influencedBy: ['TAN', 'pH', 'température', 'salinité'],
    related: ['tan', 'ph', 'temperature'],
    equations: [
      {
        label: 'Emerson — constante apparente en eau douce',
        formula: 'pKa = 0,09018 + 2729,92 / T(K)',
        applicability: 'Approximation historique pour l’équilibre NH₃/NH₄⁺ ; T en kelvins.',
      },
      {
        label: 'Fraction NH₃',
        formula: 'fNH₃ = 1 / (10^(pKa − pH) + 1)',
        applicability: 'NH₃ = TAN × fNH₃ lorsque TAN et NH₃ utilisent une base cohérente.',
      },
    ],
    cautions: ['EcoBiome doit toujours indiquer la base d’unité utilisée.', 'Le calcul simple ne remplace pas un modèle intégrant la salinité lorsque celle-ci est significative.'],
    sources: [SOURCES.emerson, SOURCES.epaAmmonia],
  },
  {
    id: 'ammonium',
    term: 'Ammonium',
    symbol: 'NH₄⁺',
    unit: 'mg/L ou mg N/L',
    category: 'azote',
    definition: 'Forme protonée et ionisée du couple ammoniac/ammonium.',
    utility: 'Constitue souvent la majeure partie du TAN aux pH usuels d’eau douce et sert de substrat aux microorganismes nitrifiants.',
    chemistry: 'Ion : NH₄⁺. Équilibre avec NH₃ selon le pH et la température.',
    influencedBy: ['TAN', 'pH', 'température', 'nitrification'],
    related: ['tan', 'ammonia', 'nitrite', 'biofilter'],
    equations: [],
    cautions: ['Un test commercial peut annoncer “ammoniaque” sans préciser s’il mesure TAN, NH₃, NH₄⁺ ou une autre base d’expression.'],
    sources: [SOURCES.emerson],
  },
  {
    id: 'nitrite',
    term: 'Nitrites',
    symbol: 'NO₂⁻',
    unit: 'mg/L',
    category: 'azote',
    metric: 'nitrite',
    definition: 'Ion nitrite, intermédiaire de l’oxydation biologique de l’azote ammoniacal vers les nitrates.',
    utility: 'Son accumulation signale souvent une nitrification incomplète ou une perturbation du biofiltre.',
    chemistry: 'Ion : NO₂⁻.',
    influencedBy: ['TAN', 'maturité du biofiltre', 'oxygène', 'température', 'pH', 'chlorures'],
    related: ['tan', 'nitrate', 'oxygen', 'chloride', 'biofilter'],
    equations: [],
    cautions: ['La toxicité dépend des espèces et de la composition ionique, notamment des chlorures.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'nitrate',
    term: 'Nitrates',
    symbol: 'NO₃⁻',
    unit: 'mg/L',
    category: 'azote',
    metric: 'nitrate',
    definition: 'Ion nitrate, produit oxydé majeur du cycle de l’azote dans un système bien oxygéné.',
    utility: 'Son accumulation renseigne sur le bilan entre production azotée, assimilation végétale, dénitrification et renouvellement d’eau.',
    chemistry: 'Ion : NO₃⁻.',
    influencedBy: ['nitrification', 'nourrissage', 'biomasse animale', 'plantes', 'changements d’eau'],
    related: ['nitrite', 'tan', 'plants'],
    equations: [],
    cautions: ['Une valeur acceptable dépend des espèces, du système et de la durée d’exposition.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'kh',
    term: 'Dureté carbonatée / pouvoir tampon',
    symbol: 'KH — HCO₃⁻ / CO₃²⁻',
    unit: '°dKH',
    category: 'acidite',
    metric: 'kh',
    definition: 'En aquariophilie, le KH est utilisé comme indicateur pratique de la réserve carbonatée et du pouvoir tampon ; il est proche de l’alcalinité dans de nombreuses eaux mais n’est pas une définition universellement identique.',
    utility: 'Une réserve alcaline suffisante limite les variations rapides de pH et fournit du carbone inorganique aux équilibres carbonate/bicarbonate.',
    chemistry: 'Espèces dominantes : bicarbonate HCO₃⁻ et carbonate CO₃²⁻ ; l’alcalinité peut aussi recevoir d’autres contributions.',
    influencedBy: ['géologie de l’eau', 'CO₂', 'acides produits par nitrification', 'changements d’eau', 'ajouts de bicarbonate'],
    related: ['ph', 'co2', 'calcium', 'gh'],
    equations: [],
    cautions: ['KH et alcalinité ne doivent pas être traités comme synonymes exacts dans tous les contextes scientifiques.'],
    sources: [SOURCES.usgsAlkalinity],
  },
  {
    id: 'gh',
    term: 'Dureté générale',
    symbol: 'GH — Ca²⁺ / Mg²⁺',
    unit: '°dGH',
    category: 'mineraux',
    metric: 'gh',
    definition: 'Indicateur de dureté lié principalement aux concentrations dissoutes de calcium Ca²⁺ et magnésium Mg²⁺.',
    utility: 'Renseigne sur la minéralisation utile à l’osmorégulation, à la physiologie des animaux et à la nutrition minérale.',
    chemistry: 'Ions principaux : Ca²⁺ et Mg²⁺.',
    influencedBy: ['géologie', 'eau de source', 'sels de reminéralisation', 'changements d’eau'],
    related: ['calcium', 'magnesium', 'conductivity', 'kh'],
    equations: [],
    cautions: ['Le GH ne donne pas séparément Ca²⁺ et Mg²⁺ ; deux eaux de même GH peuvent avoir des proportions différentes.'],
    sources: [SOURCES.usgsHardness],
  },
  {
    id: 'iron',
    term: 'Fer dissous / mesuré',
    symbol: 'Fe',
    unit: 'mg/L',
    category: 'mineraux',
    metric: 'iron',
    definition: 'Concentration de fer mesurée dans l’eau. Selon la méthode analytique, la mesure peut regrouper différentes formes dissoutes ou complexées du fer.',
    utility: 'Le fer est un micronutriment important pour les plantes et microorganismes, mais son interprétation dépend de sa forme chimique, du pH, du potentiel redox et des complexants présents.',
    chemistry: 'Principales formes ioniques rencontrées : Fe²⁺ et Fe³⁺ ; leur répartition et leur solubilité dépendent fortement des conditions du milieu.',
    influencedBy: ['pH', 'ORP / Eh', 'oxygène dissous', 'matière organique', 'fertilisation', 'substrat'],
    related: ['ph', 'orp', 'oxygen', 'plants'],
    equations: [],
    cautions: ['Une valeur totale en Fe ne décrit pas à elle seule la biodisponibilité du fer.', 'La méthode de mesure doit être conservée lorsqu’elle est connue.'],
    sources: [],
  },
  {
    id: 'conductivity',
    term: 'Conductivité électrique',
    symbol: 'κ',
    unit: 'µS/cm',
    category: 'mineraux',
    metric: 'conductivity',
    definition: 'Capacité de l’eau à conduire le courant électrique, liée aux types et quantités d’ions dissous.',
    utility: 'Très utile pour suivre la minéralisation globale, les mélanges d’eau et certaines dérives lentes.',
    chemistry: 'Grandeur collective : elle ne correspond pas à un ion unique.',
    influencedBy: ['ions dissous', 'température', 'salinité', 'évaporation', 'changements d’eau'],
    related: ['salinity', 'gh', 'chloride', 'calcium', 'magnesium'],
    equations: [],
    cautions: ['Comparer des mesures à température comparable ou compensées à une température de référence.'],
    sources: [SOURCES.usgsConductivity],
  },
  {
    id: 'chloride',
    term: 'Chlorures',
    symbol: 'Cl⁻',
    unit: 'mg/L',
    category: 'mineraux',
    metric: 'chloride',
    definition: 'Concentration de l’ion chlorure Cl⁻ dissous.',
    utility: 'Participe à l’équilibre ionique et peut modifier la sensibilité aux nitrites chez certains poissons.',
    chemistry: 'Ion : Cl⁻.',
    influencedBy: ['sel ajouté', 'source d’eau', 'évaporation', 'changements d’eau'],
    related: ['nitrite', 'salinity', 'conductivity'],
    equations: [],
    cautions: ['L’effet biologique dépend fortement de l’espèce et du contexte ionique.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'calcium',
    term: 'Calcium dissous',
    symbol: 'Ca²⁺',
    unit: 'mg/L',
    category: 'mineraux',
    metric: 'calcium',
    definition: 'Concentration de calcium sous formes dissoutes, principalement ion Ca²⁺ dans les eaux ordinaires.',
    utility: 'Contribue à la dureté, à l’osmorégulation et à de nombreux processus biologiques.',
    chemistry: 'Ion principal : Ca²⁺.',
    influencedBy: ['géologie', 'GH', 'eau de remplacement', 'reminéralisation'],
    related: ['gh', 'magnesium', 'kh', 'conductivity'],
    equations: [],
    cautions: ['Le GH ne suffit pas à déduire exactement Ca²⁺ sans connaître Mg²⁺ et les autres contributions.'],
    sources: [SOURCES.usgsHardness],
  },
  {
    id: 'magnesium',
    term: 'Magnésium dissous',
    symbol: 'Mg²⁺',
    unit: 'mg/L',
    category: 'mineraux',
    metric: 'magnesium',
    definition: 'Concentration de magnésium dissous, principalement sous forme Mg²⁺.',
    utility: 'Contribue à la dureté et intervient dans la physiologie animale et végétale.',
    chemistry: 'Ion principal : Mg²⁺.',
    influencedBy: ['géologie', 'GH', 'eau de remplacement', 'reminéralisation'],
    related: ['gh', 'calcium', 'conductivity'],
    equations: [],
    cautions: ['Comme pour Ca²⁺, le GH seul ne fournit pas sa concentration individuelle.'],
    sources: [SOURCES.usgsHardness],
  },
  {
    id: 'salinity',
    term: 'Salinité',
    symbol: 'S',
    unit: 'g/L (selon méthode)',
    category: 'mineraux',
    metric: 'salinity',
    definition: 'Mesure de la quantité globale de sels dissous ; sa définition exacte dépend de la méthode et du domaine.',
    utility: 'Influence l’osmorégulation, la conductivité et la solubilité de l’oxygène.',
    chemistry: 'Somme de nombreux ions ; pas de formule chimique unique.',
    influencedBy: ['sels dissous', 'évaporation', 'eau de remplacement', 'ajouts de sel'],
    related: ['conductivity', 'oxygen', 'oxygen_saturation', 'chloride'],
    equations: [],
    cautions: ['Ne pas convertir automatiquement conductivité ↔ salinité sans modèle adapté à la composition de l’eau.'],
    sources: [SOURCES.usgsDo, SOURCES.usgsConductivity],
  },
  {
    id: 'phosphate',
    term: 'Phosphates',
    symbol: 'PO₄³⁻',
    unit: 'mg/L',
    category: 'mineraux',
    metric: 'phosphate',
    definition: 'Famille des espèces phosphatées dissoutes ; les tests aquariophiles rapportent souvent une concentration équivalente en phosphate.',
    utility: 'Nutriment majeur pour plantes et algues ; son accumulation renseigne sur les apports et l’export biologique.',
    chemistry: 'Forme simplifiée affichée : PO₄³⁻ ; la distribution réelle H₃PO₄/H₂PO₄⁻/HPO₄²⁻/PO₄³⁻ dépend du pH.',
    influencedBy: ['nourrissage', 'décomposition', 'fertilisation', 'plantes', 'pH'],
    related: ['ph', 'algae_coverage', 'plants'],
    equations: [],
    cautions: ['Vérifier si le test est exprimé en PO₄ ou en phosphore P avant toute comparaison.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'co2',
    term: 'Dioxyde de carbone dissous',
    symbol: 'CO₂',
    unit: 'mg/L',
    category: 'gaz',
    metric: 'co2',
    definition: 'CO₂ dissous provenant de la respiration, de l’atmosphère, des injections éventuelles et des équilibres carbonatés.',
    utility: 'Source de carbone pour la photosynthèse ; ses variations sont liées au pH et au système carbonate/bicarbonate.',
    chemistry: 'CO₂(aq) ↔ H₂CO₃ ↔ HCO₃⁻ ↔ CO₃²⁻.',
    influencedBy: ['respiration', 'photosynthèse', 'aération', 'injection CO₂', 'KH / alcalinité'],
    related: ['ph', 'kh', 'oxygen', 'par_surface'],
    equations: [],
    cautions: ['Les calculs simplifiés CO₂ à partir de pH/KH reposent sur des hypothèses qui peuvent être invalides si d’autres tampons sont présents.'],
    sources: [SOURCES.usgsAlkalinity],
  },
  {
    id: 'orp',
    term: 'Potentiel d’oxydoréduction',
    symbol: 'ORP / Eh',
    unit: 'mV',
    category: 'physique',
    metric: 'orp',
    definition: 'Potentiel électrique décrivant l’état oxydant ou réducteur global mesuré avec une électrode redox.',
    utility: 'Peut aider à suivre des systèmes avancés, notamment zones réductrices, traitements oxydants ou fortes charges organiques.',
    chemistry: 'Grandeur intégrée dépendant de nombreux couples redox ; pas de formule chimique unique.',
    influencedBy: ['oxygène', 'matière organique', 'pH', 'couples redox présents', 'état de l’électrode'],
    related: ['oxygen', 'tss', 'substrate'],
    equations: [],
    cautions: ['Une valeur ORP ne permet pas à elle seule d’identifier quelle réaction chimique domine.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'tss',
    term: 'Matières en suspension',
    symbol: 'MES / TSS',
    unit: 'mg/L',
    category: 'physique',
    metric: 'tss',
    definition: 'Masse de particules retenues en suspension dans un volume d’eau selon une méthode analytique donnée.',
    utility: 'Renseigne sur les déchets particulaires, le colmatage potentiel, la turbidité et la charge organique particulaire.',
    chemistry: 'Mélange de matières minérales et organiques ; pas de formule unique.',
    influencedBy: ['nourrissage', 'fèces', 'débris végétaux', 'brassage', 'filtration mécanique'],
    related: ['oxygen', 'biofilter', 'substrate'],
    equations: [],
    cautions: ['MES/TSS et turbidité ne sont pas interchangeables : l’une mesure une masse, l’autre une propriété optique.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'par',
    term: 'Rayonnement photosynthétiquement actif',
    symbol: 'PAR / PPFD',
    unit: 'µmol photons·m⁻²·s⁻¹',
    category: 'lumiere',
    metric: 'par_surface',
    definition: 'Dans l’usage classique, domaine spectral 400–700 nm ; la quantité utile en pratique est généralement le flux de photons photosynthétiques (PPFD).',
    utility: 'Décrit bien mieux la lumière utilisable par les plantes qu’une simple puissance électrique en watts.',
    chemistry: 'Grandeur radiométrique/photonique, sans formule chimique.',
    influencedBy: ['spectre de la lampe', 'puissance optique', 'distance', 'profondeur', 'turbidité', 'ombrage'],
    related: ['par_bottom', 'water_depth', 'plants', 'algae_coverage'],
    equations: [
      {
        label: 'Définition classique du PPFD',
        formula: 'PPFD = ∫₄₀₀⁷⁰⁰ PFD(λ) dλ',
        applicability: 'Convention classique 400–700 nm ; la littérature récente discute aussi le rôle du far-red >700 nm.',
      },
    ],
    cautions: ['Ne pas confondre watts électriques, lux et PPFD.', 'La valeur reçue au fond peut être très inférieure à celle de surface.'],
    sources: [SOURCES.par, SOURCES.parRadiometry],
  },
  {
    id: 'water_depth',
    term: 'Profondeur d’eau',
    symbol: 'h',
    unit: 'cm',
    category: 'physique',
    metric: 'water_depth',
    definition: 'Hauteur de colonne d’eau entre la surface et le point considéré.',
    utility: 'Influence la pression hydrostatique, la transmission lumineuse, les gradients thermiques et la circulation.',
    chemistry: 'Grandeur géométrique.',
    influencedBy: ['niveau de remplissage', 'forme du contenant'],
    related: ['par_surface', 'par_bottom', 'temperature'],
    equations: [],
    cautions: ['La profondeur utile pour une plante ou un capteur dépend de sa position réelle dans le milieu.'],
    sources: [SOURCES.usgsWater],
  },
  {
    id: 'biofilter',
    term: 'Biofiltre',
    symbol: '—',
    unit: '—',
    category: 'biologie',
    definition: 'Support et environnement hydraulique hébergeant une communauté microbienne qui transforme notamment les composés azotés.',
    utility: 'Permet de relier charge biologique, TAN, nitrites, oxygène, débit et maturité microbienne.',
    chemistry: 'Processus central : oxydation de NH₃/NH₄⁺ vers NO₂⁻ puis NO₃⁻ dans les conditions nitrifiantes.',
    influencedBy: ['surface spécifique', 'débit', 'oxygène', 'température', 'pH', 'maturité', 'nettoyage'],
    related: ['tan', 'nitrite', 'nitrate', 'oxygen', 'specific_surface', 'flow'],
    equations: [],
    cautions: ['La présence physique d’un filtre ne garantit pas une capacité biologique mature.'],
    sources: [SOURCES.epaAmmonia],
  },
  {
    id: 'nitrification',
    term: 'Nitrification',
    symbol: 'NH₄⁺/NH₃ → NO₂⁻ → NO₃⁻',
    unit: '—',
    category: 'biologie',
    definition: 'Ensemble de processus microbiens oxydant l’azote ammoniacal vers les nitrites puis les nitrates.',
    utility: 'Explique une part majeure de la transformation des déchets azotés dans les systèmes oxygénés.',
    chemistry: 'Chaîne simplifiée : NH₄⁺/NH₃ → NO₂⁻ → NO₃⁻.',
    influencedBy: ['oxygène', 'pH', 'température', 'alcalinité', 'maturité du biofiltre', 'charge TAN'],
    related: ['tan', 'nitrite', 'nitrate', 'oxygen', 'kh', 'biofilter'],
    equations: [],
    cautions: ['La chaîne simplifiée ne décrit pas toute la diversité microbienne ni toutes les voies de l’azote.'],
    sources: [SOURCES.epaAmmonia],
  },
  {
    id: 'biomass',
    term: 'Biomasse animale',
    symbol: 'm',
    unit: 'g',
    category: 'biologie',
    definition: 'Masse totale connue des animaux suivis dans le milieu.',
    utility: 'Meilleure approximation de la charge biologique que le seul nombre d’individus lorsque les tailles diffèrent.',
    chemistry: 'Grandeur biologique, pas une espèce chimique.',
    influencedBy: ['effectif', 'masse moyenne', 'croissance', 'mortalité', 'retraits'],
    related: ['feeding', 'tan', 'oxygen'],
    equations: [
      {
        label: 'Biomasse estimée',
        formula: 'Biomasse = effectif × masse moyenne individuelle',
        applicability: 'Approximation si la masse moyenne est représentative de la population.',
      },
    ],
    cautions: ['Une moyenne masque la dispersion des tailles.'],
    sources: [],
  },
  {
    id: 'feeding',
    term: 'Nourrissage',
    symbol: '—',
    unit: 'g/j ou g/événement',
    category: 'biologie',
    definition: 'Entrée de matière organique et de nutriments sous forme d’aliment distribué.',
    utility: 'C’est l’un des principaux flux qui génèrent respiration, déchets, TAN, matières en suspension et nutriments.',
    chemistry: 'La composition dépend de l’aliment : protéines, lipides, glucides, minéraux, eau.',
    influencedBy: ['biomasse animale', 'type d’aliment', 'fréquence', 'température', 'appétit'],
    related: ['biomass', 'tan', 'tss', 'oxygen', 'phosphate'],
    equations: [],
    cautions: ['La masse distribuée n’est pas égale à la masse réellement ingérée.'],
    sources: [],
  },
  {
    id: 'specific_surface',
    term: 'Surface spécifique du média',
    symbol: 'SSA',
    unit: 'm²/L',
    category: 'biologie',
    definition: 'Surface théorique disponible par volume de média filtrant.',
    utility: 'Aide à décrire le support potentiel de biofilm et à comparer des médias, sans constituer à elle seule une capacité de nitrification.',
    chemistry: 'Grandeur géométrique.',
    influencedBy: ['structure du média', 'porosité', 'colmatage', 'biofilm'],
    related: ['biofilter', 'flow', 'tss'],
    equations: [],
    cautions: ['Les surfaces annoncées par les fabricants ne sont pas toujours mesurées selon la même méthode ni entièrement biologiquement accessibles.'],
    sources: [],
  },
  {
    id: 'flow',
    term: 'Débit de circulation',
    symbol: 'Q',
    unit: 'L/h',
    category: 'physique',
    definition: 'Volume d’eau traversant un point ou un système par unité de temps.',
    utility: 'Conditionne le transport d’oxygène, des déchets et des nutriments vers les systèmes de filtration.',
    chemistry: 'Grandeur hydraulique.',
    influencedBy: ['pompe', 'hauteur manométrique', 'pertes de charge', 'colmatage', 'niveau d’eau'],
    related: ['biofilter', 'oxygen', 'tss'],
    equations: [
      {
        label: 'Taux de renouvellement hydraulique',
        formula: 'Turnover (h⁻¹) = Q (L/h) / volume d’eau (L)',
        applicability: 'Indicateur hydraulique simple ; ne garantit pas une circulation homogène dans tout le bac.',
      },
    ],
    cautions: ['Le débit constructeur à vide peut être très différent du débit réellement mesuré en fonctionnement.'],
    sources: [],
  },
  {
    id: 'algae_coverage',
    term: 'Couverture algale',
    symbol: 'Algues',
    unit: '%',
    category: 'biologie',
    metric: 'algae_coverage',
    definition: 'Estimation de la proportion d’une surface ou d’une zone du milieu visiblement couverte par des algues.',
    utility: 'Permet de suivre l’évolution de la production algale et de la mettre en relation avec lumière, nutriments, herbivorie et interventions.',
    chemistry: 'Ce n’est pas une espèce chimique mais un indicateur biologique de couverture.',
    influencedBy: ['PAR / lumière', 'azote disponible', 'phosphore', 'CO₂', 'température', 'herbivorie', 'entretien'],
    related: ['par', 'nitrate', 'phosphate', 'co2', 'periphyton'],
    equations: [],
    cautions: ['Un pourcentage de couverture ne mesure ni la biomasse algale exacte ni l’identité des espèces présentes.'],
    sources: [],
  },
  {
    id: 'periphyton',
    term: 'Périphyton',
    symbol: '—',
    unit: '% de couverture (dans EcoBiome)',
    category: 'biologie',
    metric: 'periphyton_coverage',
    definition: 'Communauté attachée aux surfaces immergées : algues, bactéries, champignons, microorganismes et matières associées.',
    utility: 'Peut contribuer à la production primaire, au recyclage des nutriments et à la nourriture de certains organismes.',
    chemistry: 'Communauté biologique complexe.',
    influencedBy: ['lumière', 'nutriments', 'broutage', 'surface disponible', 'débit'],
    related: ['par_surface', 'phosphate', 'nitrate', 'algae_coverage'],
    equations: [],
    cautions: ['Le pourcentage de couverture est un indice pratique, pas une mesure directe de biomasse.'],
    sources: [],
  },
  {
    id: 'analytical_constituents',
    term: 'Constituants analytiques d’un aliment',
    symbol: '—',
    unit: '% ou unité déclarée',
    category: 'biologie',
    definition: 'Valeurs analytiques déclarées pour caractériser un aliment, par exemple protéines brutes, matières grasses, fibres, humidité, cendres ou phosphore.',
    utility: 'Elles permettent de transformer une masse d’aliment distribuée en apports quantitatifs structurés plutôt qu’en simple nom de produit.',
    chemistry: 'Analyse proximale : eau, protéines brutes, lipides, fibres, cendres et autres fractions selon la fiche disponible.',
    influencedBy: ['formulation', 'matières premières', 'procédé de fabrication', 'lot et méthode analytique'],
    related: ['crude_protein', 'dry_matter', 'feeding'],
    equations: [],
    cautions: ['Une valeur absente de la fiche produit doit rester inconnue ; EcoBiome ne doit pas l’inventer.', 'Les données peuvent être exprimées sur produit tel que distribué ou sur matière sèche selon la source.'],
    sources: [SOURCES.faoFeedAnalysis],
  },
  {
    id: 'crude_protein',
    term: 'Protéines brutes',
    symbol: 'PB / CP',
    unit: '%',
    category: 'biologie',
    definition: 'Estimation conventionnelle de la teneur protéique d’un aliment à partir de son azote total.',
    utility: 'Elle fournit une première estimation de l’azote apporté par l’aliment, nécessaire au bilan de charge azotée.',
    chemistry: 'Convention usuelle : les protéines sont supposées contenir en moyenne environ 16 % d’azote, d’où le facteur 6,25.',
    influencedBy: ['composition de l’aliment', 'méthode analytique', 'azote non protéique'],
    related: ['protein_nitrogen', 'feeding', 'tan'],
    equations: [
      {
        label: 'Conversion conventionnelle',
        formula: 'Protéines brutes (%) = N total (%) × 6,25',
        applicability: 'Facteur empirique usuel ; la teneur réelle en azote des protéines peut varier.',
      },
    ],
    cautions: ['« Protéines brutes » ne signifie pas protéines digestibles.', 'Le facteur 6,25 est une convention et non une constante universelle de toutes les protéines.'],
    sources: [SOURCES.faoFeedAnalysis],
  },
  {
    id: 'protein_nitrogen',
    term: 'Azote protéique estimé',
    symbol: 'Nprotéines',
    unit: 'mg N',
    category: 'azote',
    definition: 'Quantité d’azote estimée à partir de la masse de protéines brutes apportée par un aliment.',
    utility: 'EcoBiome l’utilise comme bilan d’entrée avant toute hypothèse sur digestion, croissance ou excrétion.',
    chemistry: 'Azote contenu dans la fraction assimilée conventionnellement aux protéines brutes.',
    influencedBy: ['masse d’aliment', 'protéines brutes'],
    related: ['crude_protein', 'tan', 'nitrogen_retention'],
    equations: [
      {
        label: 'Inversion du facteur protéines/azote',
        formula: 'Nprotéines (mg) ≈ protéines brutes (g) / 6,25 × 1000',
        applicability: 'Bilan conventionnel d’entrée, pas mesure de l’azote effectivement excrété.',
      },
    ],
    cautions: ['Cet azote n’est pas équivalent au TAN produit : une partie peut être retenue dans la biomasse ou suivre d’autres voies.'],
    sources: [SOURCES.faoFeedAnalysis, SOURCES.rasFeeding],
  },
  {
    id: 'dry_matter',
    term: 'Matière sèche',
    symbol: 'MS / DM',
    unit: 'g ou %',
    category: 'biologie',
    definition: 'Fraction de l’aliment restante après retrait de l’eau.',
    utility: 'Elle aide à comparer des aliments de teneurs en eau très différentes, notamment sec, congelé, gel ou nourriture fraîche.',
    chemistry: 'Grandeur de composition ; matière sèche = masse totale − eau.',
    influencedBy: ['humidité de l’aliment', 'forme de l’aliment', 'stockage'],
    related: ['analytical_constituents', 'feeding'],
    equations: [
      {
        label: 'Matière sèche à partir de l’humidité',
        formula: 'MS (g) = masse distribuée × (100 − humidité %) / 100',
        applicability: 'Lorsque l’humidité est déclarée sur le produit tel que distribué.',
      },
    ],
    cautions: ['Comparer deux pourcentages nutritionnels nécessite de vérifier s’ils sont exprimés sur produit brut ou matière sèche.'],
    sources: [SOURCES.faoFeedAnalysis],
  },
  {
    id: 'feed_rate',
    term: 'Ration relative à la biomasse',
    symbol: 'R',
    unit: '% de biomasse / événement',
    category: 'biologie',
    definition: 'Rapport entre la masse d’aliment distribuée lors d’un événement et la biomasse animale ciblée connue.',
    utility: 'Permet de comparer un nourrissage entre populations de tailles différentes et d’identifier une entrée alimentaire disproportionnée.',
    chemistry: 'Grandeur de flux biologique, sans formule chimique propre.',
    influencedBy: ['masse d’aliment distribuée', 'biomasse ciblée'],
    related: ['feeding', 'biomass', 'digestibility'],
    equations: [
      {
        label: 'Ration de l’événement',
        formula: 'R (%) = aliment distribué (g) / biomasse ciblée (g) × 100',
        applicability: 'Décrit l’événement enregistré ; ne doit pas être confondu avec une ration quotidienne si plusieurs repas sont distribués.',
      },
    ],
    cautions: ['Une ration appropriée dépend de l’espèce, du stade, de la température, de l’aliment et de la stratégie d’élevage.'],
    sources: [SOURCES.rasFeeding],
  },
  {
    id: 'digestibility',
    term: 'Digestibilité',
    symbol: 'ADC',
    unit: '%',
    category: 'biologie',
    definition: 'Fraction d’un nutriment ingéré qui est digérée et absorbée plutôt qu’éliminée dans les fèces.',
    utility: 'Elle est indispensable pour passer d’un bilan d’aliment distribué à une prédiction réaliste des déchets dissous et solides.',
    chemistry: 'S’applique séparément aux protéines, lipides, énergie, phosphore et autres nutriments.',
    influencedBy: ['espèce', 'stade de vie', 'ingrédients', 'procédé de fabrication', 'température', 'ration'],
    related: ['feeding', 'nitrogen_retention', 'protein_nitrogen', 'tss'],
    equations: [],
    cautions: ['EcoBiome N9 V1 ne suppose aucune digestibilité universelle lorsqu’elle n’est pas documentée.'],
    sources: [SOURCES.rasFeeding],
  },
  {
    id: 'nitrogen_retention',
    term: 'Rétention azotée',
    symbol: 'Nretenu',
    unit: '% ou mg N',
    category: 'azote',
    definition: 'Part de l’azote ingéré conservée dans la croissance et les tissus plutôt que rejetée vers l’environnement.',
    utility: 'Elle est nécessaire pour convertir l’azote alimentaire en excrétion prévisible de TAN et autres pertes azotées.',
    chemistry: 'Bilan de masse de l’élément azote N.',
    influencedBy: ['espèce', 'croissance', 'qualité du régime', 'digestibilité', 'température', 'ration'],
    related: ['protein_nitrogen', 'tan', 'digestibility', 'biomass'],
    equations: [],
    cautions: ['La rétention varie selon l’espèce, le régime et les conditions ; une valeur issue d’une autre espèce ne doit pas être appliquée automatiquement.'],
    sources: [SOURCES.rasFeeding],
  },
  {
    id: 'stoichiometric_upper_bound',
    term: 'Borne stœchiométrique',
    symbol: 'borne max.',
    unit: 'selon la grandeur',
    category: 'biologie',
    definition: 'Valeur théorique calculée en supposant une conversion maximale selon un bilan chimique, utilisée comme limite et non comme prédiction du résultat réel.',
    utility: 'Permet à EcoBiome de quantifier immédiatement ce qui serait chimiquement possible tout en séparant clairement l’incertitude biologique.',
    chemistry: 'Exemple nitrification : l’oxydation d’ammoniac-N requiert théoriquement environ 4,57 g O₂ et consomme environ 7,14 g d’alcalinité exprimée en CaCO₃ par g de N oxydé.',
    influencedBy: ['hypothèses du bilan', 'quantité d’azote disponible'],
    related: ['protein_nitrogen', 'tan', 'oxygen', 'kh', 'nitrification'],
    equations: [
      {
        label: 'Oxygène théorique de nitrification',
        formula: 'O₂ ≈ 4,57 × NH₄-N oxydé',
        applicability: 'Borne stœchiométrique théorique ; la demande totale du système inclut aussi d’autres consommations d’oxygène.',
      },
      {
        label: 'Alcalinité théorique consommée',
        formula: 'Alcalinité ≈ 7,14 × NH₄-N oxydé, exprimée en CaCO₃',
        applicability: 'Relation stœchiométrique de nitrification, pas mesure directe du KH observé.',
      },
    ],
    cautions: ['Une borne maximale ne doit jamais être affichée comme une variation physico-chimique réellement attendue.', 'Les observations de l’eau ne sont pas modifiées par ce calcul.'],
    sources: [SOURCES.epaNitrification],
  },
];

export const GLOSSARY_BY_METRIC: Partial<Record<Metric, GlossaryEntry>> =
  Object.fromEntries(
    SCIENTIFIC_GLOSSARY
      .filter((entry) => entry.metric)
      .map((entry) => [entry.metric as Metric, entry]),
  ) as Partial<Record<Metric, GlossaryEntry>>;

const METRIC_GLOSSARY_ALIASES: Partial<Record<Metric, string>> = {
  par_bottom: 'par',
};

export function getGlossaryEntryForMetric(metric: Metric): GlossaryEntry | undefined {
  const direct = SCIENTIFIC_GLOSSARY.find((entry) => entry.metric === metric);
  if (direct) {
    return direct;
  }
  const aliasId = METRIC_GLOSSARY_ALIASES[metric];
  return aliasId ? SCIENTIFIC_GLOSSARY.find((entry) => entry.id === aliasId) : undefined;
}
